### ISSUE TITLE
speedwire search

### ISSUE THREAD

**Issue by lansi002** [rklomp/Domoticz-SMA-SunnyBoy#1]
Hello, in the past i had a SMA plugin which works with csv files and the plugin communicated with the SMA sunnyboy without configuring an ip-number. It did some sort of speedwire broadcast and based on that the SAM sunnyboy gave a respons with the current measurments.

Is it possible to add that function to your plugin ?

I do not like to have static ip-numbers in my network.
Hopefully somebody is able to add that function.

Kind regards,
Andre

**Comment by rklomp** [comment]
That would require a completely new/different plugin and technology so not in scope of this plugin
